### ISSUE TITLE
Warning free Albany build on blake failing to build

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#1078]
See https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=218499. 

```[Albany/src/disc/stk/STKConnManager.cpp:125](https://blob/master/Albany/src/disc/stk/STKConnManager.cpp#L125):30: error: comparison of integer expressions of different signedness: 'int' and 'unsigned int' [-Werror=sign-compare]```

**Comment by bartgol** [comment]
Fixed by 76cca061d. We can close tomorrow.

**Comment by jewatkins** [comment]
looks like my cronjob was removed, I just added it back in.

**Comment by ikalash** [comment]
So this is not fixed...  https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=224586 .  Still have unused vars in STK.

**Comment by bartgol** [comment]
I'm fixing other stuff, so I can remove those vars in the process.

**Comment by ikalash** [comment]
Thank you!
