### ISSUE TITLE
Blake gcc-no-warn build broken

### ISSUE THREAD

**Issue by jewatkins** [sandialabs/Albany#852]
@bartgol Looks like there were some sign/unsigned comparison issues from your changes to `GatherSolution` yesterday:
https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=40432

**Comment by bartgol** [comment]
Ah, I did those changes to fix some warning, but I guess I ended up creating more. I'll fix them.

**Comment by bartgol** [comment]
6b6eb0f29 should fix the warnings. We'll see tomorrow (more likely Monday).

**Comment by ikalash** [comment]
FYI, the warning free build is still broken.  @bartgol can you please have a look?

**Comment by bartgol** [comment]
Done. 82f3253bb
